services:
  php-cli:
    build:
      context: ./docker/php-cli
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_CACHE_DIR=/tmp/composer/cache
      - RARUS_ECHO_API_KEY=${RARUS_ECHO_API_KEY:-}
      - RARUS_ECHO_USER_ID=${RARUS_ECHO_USER_ID:-00000000-0000-0000-0000-000000000000}
      - RARUS_ECHO_BASE_URL=${RARUS_ECHO_BASE_URL:-https://production-ai-ui-api.ai.rarus-cloud.ru}
    networks:
      - rarus-echo-network

networks:
  rarus-echo-network:
    driver: bridge
